/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UpdatesRouteImport } from './routes/updates'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HomeRouteImport } from './routes/home'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DirectoryIndexRouteImport } from './routes/directory/index'
import { Route as PostPostIDRouteImport } from './routes/post.$postID'
import { Route as DirectoryDirectoryIDRouteImport } from './routes/directory/$directoryID'

const UpdatesRoute = UpdatesRouteImport.update({
  id: '/updates',
  path: '/updates',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DirectoryIndexRoute = DirectoryIndexRouteImport.update({
  id: '/directory/',
  path: '/directory/',
  getParentRoute: () => rootRouteImport,
} as any)
const PostPostIDRoute = PostPostIDRouteImport.update({
  id: '/post/$postID',
  path: '/post/$postID',
  getParentRoute: () => rootRouteImport,
} as any)
const DirectoryDirectoryIDRoute = DirectoryDirectoryIDRouteImport.update({
  id: '/directory/$directoryID',
  path: '/directory/$directoryID',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/signup': typeof SignupRoute
  '/updates': typeof UpdatesRoute
  '/directory/$directoryID': typeof DirectoryDirectoryIDRoute
  '/post/$postID': typeof PostPostIDRoute
  '/directory': typeof DirectoryIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/signup': typeof SignupRoute
  '/updates': typeof UpdatesRoute
  '/directory/$directoryID': typeof DirectoryDirectoryIDRoute
  '/post/$postID': typeof PostPostIDRoute
  '/directory': typeof DirectoryIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/signup': typeof SignupRoute
  '/updates': typeof UpdatesRoute
  '/directory/$directoryID': typeof DirectoryDirectoryIDRoute
  '/post/$postID': typeof PostPostIDRoute
  '/directory/': typeof DirectoryIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/home'
    | '/login'
    | '/profile'
    | '/signup'
    | '/updates'
    | '/directory/$directoryID'
    | '/post/$postID'
    | '/directory'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/home'
    | '/login'
    | '/profile'
    | '/signup'
    | '/updates'
    | '/directory/$directoryID'
    | '/post/$postID'
    | '/directory'
  id:
    | '__root__'
    | '/'
    | '/home'
    | '/login'
    | '/profile'
    | '/signup'
    | '/updates'
    | '/directory/$directoryID'
    | '/post/$postID'
    | '/directory/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HomeRoute: typeof HomeRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  SignupRoute: typeof SignupRoute
  UpdatesRoute: typeof UpdatesRoute
  DirectoryDirectoryIDRoute: typeof DirectoryDirectoryIDRoute
  PostPostIDRoute: typeof PostPostIDRoute
  DirectoryIndexRoute: typeof DirectoryIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/updates': {
      id: '/updates'
      path: '/updates'
      fullPath: '/updates'
      preLoaderRoute: typeof UpdatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/directory/': {
      id: '/directory/'
      path: '/directory'
      fullPath: '/directory'
      preLoaderRoute: typeof DirectoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/post/$postID': {
      id: '/post/$postID'
      path: '/post/$postID'
      fullPath: '/post/$postID'
      preLoaderRoute: typeof PostPostIDRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/directory/$directoryID': {
      id: '/directory/$directoryID'
      path: '/directory/$directoryID'
      fullPath: '/directory/$directoryID'
      preLoaderRoute: typeof DirectoryDirectoryIDRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HomeRoute: HomeRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  SignupRoute: SignupRoute,
  UpdatesRoute: UpdatesRoute,
  DirectoryDirectoryIDRoute: DirectoryDirectoryIDRoute,
  PostPostIDRoute: PostPostIDRoute,
  DirectoryIndexRoute: DirectoryIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
