/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UpdatesRouteImport } from './routes/updates'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as HomeRouteImport } from './routes/home'
import { Route as DirectoryRouteImport } from './routes/directory'
import { Route as IndexRouteImport } from './routes/index'

const UpdatesRoute = UpdatesRouteImport.update({
  id: '/updates',
  path: '/updates',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const DirectoryRoute = DirectoryRouteImport.update({
  id: '/directory',
  path: '/directory',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/directory': typeof DirectoryRoute
  '/home': typeof HomeRoute
  '/profile': typeof ProfileRoute
  '/updates': typeof UpdatesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/directory': typeof DirectoryRoute
  '/home': typeof HomeRoute
  '/profile': typeof ProfileRoute
  '/updates': typeof UpdatesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/directory': typeof DirectoryRoute
  '/home': typeof HomeRoute
  '/profile': typeof ProfileRoute
  '/updates': typeof UpdatesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/directory' | '/home' | '/profile' | '/updates'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/directory' | '/home' | '/profile' | '/updates'
  id: '__root__' | '/' | '/directory' | '/home' | '/profile' | '/updates'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DirectoryRoute: typeof DirectoryRoute
  HomeRoute: typeof HomeRoute
  ProfileRoute: typeof ProfileRoute
  UpdatesRoute: typeof UpdatesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/updates': {
      id: '/updates'
      path: '/updates'
      fullPath: '/updates'
      preLoaderRoute: typeof UpdatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/directory': {
      id: '/directory'
      path: '/directory'
      fullPath: '/directory'
      preLoaderRoute: typeof DirectoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DirectoryRoute: DirectoryRoute,
  HomeRoute: HomeRoute,
  ProfileRoute: ProfileRoute,
  UpdatesRoute: UpdatesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
